### PR TITLE
Update modDesc.xml

### PR DESCRIPTION
**Pull request by vitalii2011**

### CODE REVIEW

**Comment by 4c65736975** [comment]
Not fully translated

**Comment by vitalii2011** [comment]
Are you talking about this? 
PJQjalw

**Review by 4c65736975 — COMMENTED** [review]
Accepted but rejected due to an upcoming update

**Comment by 4c65736975** [comment]
Yes, that's what I meant, thanks for the correction. For now, I am rejecting the pull request due to the update that is being prepared, which will create additional translation files due to the increased amount of additional text to be translated. Please keep in mind when a new branch appears and then create a pull request with translation ;)

**Pull request closed without merging**
